Standardization
shyamrallapalli/biojs-vcf pull request #6
Opened 2017-06-02 10:54 UTC by StuntsPT

Documentation standardizations, better "Standard JS" conformance, bumped package versions and implemented "Standard JS" tests.

2017-08-23 10:03 UTC, bmpvieira requested changes
Looks good, just needs two small changes.

2017-08-23 10:03 UTC, bmpvieira commented on lib/index.js
> +            // ##fileformat=VCFv4.1
Can you please fix the indentation of the comments here and below?

2017-08-23 10:03 UTC, bmpvieira commented on package.json
> +    "test": "standard && dependency-check ."
You should keep the mocha testing here, like `standard && dependency-check . && mocha`

2017-08-25 21:56 UTC, StuntsPT commented
These two commits should handle your concerns. Unless I got the indentation wrong...

2017-08-28 15:43 UTC, bmpvieira approved these changes

2017-08-28 15:43 UTC, merged